<a href="https://colab.research.google.com/github/CaroBrambila/Actividad-3.1-y-3.2-Valores-Nulos-/blob/main/Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
data= pd.read_csv("Ventas_totales.csv")
data.head(5)

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros
0,01/01/2017,27858.9,27477.3,27858872.08,27591730.13,267141.956,27858872.08,1.023010e+07,6864575.384,9047205.493,...,6705475.318,9.459063e+05,2880656.169,2606192.942,1.050314e+06,340777.3882,4397543.671,772371.8476,1838507.096,2806660.309
1,01/02/2017,25994.2,25223.4,25994200.17,25749179.40,245020.769,25994200.17,9.719067e+06,6438494.011,8309150.301,...,6576624.803,9.256186e+05,2855639.900,2600083.591,1.026167e+06,328288.6951,4053283.771,672290.5165,1257661.903,2354084.901
2,01/03/2017,27780.0,26334.3,27780006.52,27472228.72,307777.804,27780006.52,1.024444e+07,6908522.962,8845010.494,...,7437264.174,1.016148e+06,3188259.169,2824976.726,1.075526e+06,353335.1548,4354197.611,667696.6653,1305674.917,2266189.277
3,01/04/2017,29134.3,27045.9,29134272.22,28827479.49,306792.733,29134272.22,1.031263e+07,7454251.800,9458166.682,...,8211244.093,1.132396e+06,3257140.159,3006158.760,1.037213e+06,359694.4537,4355706.646,838948.2458,1535726.345,2146755.887
4,01/05/2017,27969.0,25631.9,27969004.68,27569311.41,399693.262,27969004.68,1.014761e+07,6735747.319,9220929.862,...,7651058.084,1.033082e+06,3232635.767,2799142.123,9.826512e+05,336568.0085,4206101.605,915895.1498,1824462.036,2117971.483

In [14]:
##Eliminar filas innecesarias
data1= pd.read_csv("Ventas_totales.csv", skiprows=1)
data1

,01/01/2017,27858.9,27477.3,27858872.08,27591730.13,267141.956,27858872.08.1,10230100.13,6864575.384,9047205.493,...,6705475.318,945906.3068,2880656.169,2606192.942,1050313.638,340777.3882,4397543.671,772371.8476,1838507.096,2806660.309
0,01/02/2017,25994.2,25223.4,2.599420e+07,2.574918e+07,2.450208e+05,2.599420e+07,9.719067e+06,6.438494e+06,8.309150e+06,...,6.576625e+06,9.256186e+05,2.855640e+06,2.600084e+06,1.026167e+06,3.282887e+05,4.053284e+06,6.722905e+05,1.257662e+06,2.354085e+06
1,01/03/2017,27780.0,26334.3,2.778001e+07,2.747223e+07,3.077778e+05,2.778001e+07,1.024444e+07,6.908523e+06,8.845010e+06,...,7.437264e+06,1.016148e+06,3.188259e+06,2.824977e+06,1.075526e+06,3.533352e+05,4.354198e+06,6.676967e+05,1.305675e+06,2.266189e+06
2,01/04/2017,29134.3,27045.9,2.913427e+07,2.882748e+07,3.067927e+05,2.913427e+07,1.031263e+07,7.454252e+06,9.458167e+06,...,8.211244e+06,1.132396e+06,3.257140e+06,3.006159e+06,1.037213e+06,3.596945e+05,4.355707e+06,8.389482e+05,1.535726e+06,2.146756e+06
3,01/05/2017,27969.0,25631.9,2.796900e+07,2.756931e+07,3.996933e+05,2.796900e+07,1.014761e+07,6.735747e+06,9.220930e+06,...,7.651058e+06,1.033082e+06,3.232636e+06,2.799142e+06,9.826512e+05,3.365680e+05,4.206102e+06,9.158951e+05,1.824462e+06,2.117971e+06
4,01/06/2017,29132.7,26365.4,2.913271e+07,2.876387e+07,3.688473e+05,2.913271e+07,1.056549e+07,7.337457e+06,9.196110e+06,...,7.911936e+06,1.083494e+06,3.322050e+06,2.883229e+06,9.522033e+05,3.451141e+05,4.277890e+06,1.001572e+06,1.893542e+06,2.358093e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,01/01/2022,154517.1,45463.4,1.545171e+08,1.496976e+08,4.819480e+06,1.545171e+08,4.696260e+07,4.605365e+07,5.404833e+07,...,3.750517e+07,4.860318e+06,1.610477e+07,1.740849e+07,6.138441e+06,1.401929e+06,2.133021e+07,3.782646e+06,1.218755e+07,1.343307e+07
60,01/02/2022,152202.6,23802.1,1.522026e+08,1.484065e+08,3.796044e+06,1.522026e+08,4.629096e+07,4.528358e+07,5.370589e+07,...,3.820979e+07,5.045920e+06,1.613982e+07,1.826074e+07,6.436028e+06,1.370640e+06,2.030545e+07,NaN,9.189746e+06,1.330139e+07
61,01/03/2022,16.5,24612.4,1.689825e+08,1.643211e+08,4.661350e+05,1.689825e+08,5.126208e+07,4.736436e+07,NaN,...,4.541886e+07,5.922820e+06,1.841916e+07,2.082760e+07,6.886240e+06,1.589119e+06,2.294201e+07,3.912852e+06,1.089879e+07,NaN
62,01/04/2022,177148.1,24140.5,1.771481e+08,1.730038e+08,4.144284e+06,1.771481e+08,5.319000e+07,5.006397e+07,6.535759e+07,...,4.999168e+07,6.746167e+06,1.930946e+07,2.287784e+07,6.510666e+06,1.719459e+06,2.313127e+07,4.228054e+06,NaN,1.191048e+07
63,01/05/2022,179639.2,23234.2,1.796392e+08,1.753585e+08,4.280751e+06,1.796392e+08,5.273811e+07,4.988679e+07,6.807009e+07,...,5.015035e+07,6.667330e+06,2.012112e+07,2.284153e+07,6.314109e+06,1.779483e+06,2.357864e+07,5.213153e+06,1.203960e+07,1.234998e+07

In [15]:
##Carga desde un archivo .csv sin indice
data=pd.read_csv("Ventas_totales.csv")
data.head(3)

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros
0,01/01/2017,27858.9,27477.3,27858872.08,27591730.13,267141.956,27858872.08,1.023010e+07,6864575.384,9047205.493,...,6705475.318,9.459063e+05,2880656.169,2606192.942,1050313.638,340777.3882,4397543.671,772371.8476,1838507.096,2806660.309
1,01/02/2017,25994.2,25223.4,25994200.17,25749179.40,245020.769,25994200.17,9.719067e+06,6438494.011,8309150.301,...,6576624.803,9.256186e+05,2855639.900,2600083.591,1026166.544,328288.6951,4053283.771,672290.5165,1257661.903,2354084.901
2,01/03/2017,27780.0,26334.3,27780006.52,27472228.72,307777.804,27780006.52,1.024444e+07,6908522.962,8845010.494,...,7437264.174,1.016148e+06,3188259.169,2824976.726,1075525.842,353335.1548,4354197.611,667696.6653,1305674.917,2266189.277

In [16]:
##Identificar los valores nulos
valores_nulos=data.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            6
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
dtype: int64

METODOS DE SUSTITUCIÓN

In [21]:
##creamos una copia del dataframe
data2=data1.copy()
data2

,01/01/2017,27858.9,27477.3,27858872.08,27591730.13,267141.956,27858872.08.1,10230100.13,6864575.384,9047205.493,...,6705475.318,945906.3068,2880656.169,2606192.942,1050313.638,340777.3882,4397543.671,772371.8476,1838507.096,2806660.309
0,01/02/2017,25994.2,25223.4,2.599420e+07,2.574918e+07,2.450208e+05,2.599420e+07,9.719067e+06,6.438494e+06,8.309150e+06,...,6.576625e+06,9.256186e+05,2.855640e+06,2.600084e+06,1.026167e+06,3.282887e+05,4.053284e+06,6.722905e+05,1.257662e+06,2.354085e+06
1,01/03/2017,27780.0,26334.3,2.778001e+07,2.747223e+07,3.077778e+05,2.778001e+07,1.024444e+07,6.908523e+06,8.845010e+06,...,7.437264e+06,1.016148e+06,3.188259e+06,2.824977e+06,1.075526e+06,3.533352e+05,4.354198e+06,6.676967e+05,1.305675e+06,2.266189e+06
2,01/04/2017,29134.3,27045.9,2.913427e+07,2.882748e+07,3.067927e+05,2.913427e+07,1.031263e+07,7.454252e+06,9.458167e+06,...,8.211244e+06,1.132396e+06,3.257140e+06,3.006159e+06,1.037213e+06,3.596945e+05,4.355707e+06,8.389482e+05,1.535726e+06,2.146756e+06
3,01/05/2017,27969.0,25631.9,2.796900e+07,2.756931e+07,3.996933e+05,2.796900e+07,1.014761e+07,6.735747e+06,9.220930e+06,...,7.651058e+06,1.033082e+06,3.232636e+06,2.799142e+06,9.826512e+05,3.365680e+05,4.206102e+06,9.158951e+05,1.824462e+06,2.117971e+06
4,01/06/2017,29132.7,26365.4,2.913271e+07,2.876387e+07,3.688473e+05,2.913271e+07,1.056549e+07,7.337457e+06,9.196110e+06,...,7.911936e+06,1.083494e+06,3.322050e+06,2.883229e+06,9.522033e+05,3.451141e+05,4.277890e+06,1.001572e+06,1.893542e+06,2.358093e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,01/01/2022,154517.1,45463.4,1.545171e+08,1.496976e+08,4.819480e+06,1.545171e+08,4.696260e+07,4.605365e+07,5.404833e+07,...,3.750517e+07,4.860318e+06,1.610477e+07,1.740849e+07,6.138441e+06,1.401929e+06,2.133021e+07,3.782646e+06,1.218755e+07,1.343307e+07
60,01/02/2022,152202.6,23802.1,1.522026e+08,1.484065e+08,3.796044e+06,1.522026e+08,4.629096e+07,4.528358e+07,5.370589e+07,...,3.820979e+07,5.045920e+06,1.613982e+07,1.826074e+07,6.436028e+06,1.370640e+06,2.030545e+07,NaN,9.189746e+06,1.330139e+07
61,01/03/2022,16.5,24612.4,1.689825e+08,1.643211e+08,4.661350e+05,1.689825e+08,5.126208e+07,4.736436e+07,NaN,...,4.541886e+07,5.922820e+06,1.841916e+07,2.082760e+07,6.886240e+06,1.589119e+06,2.294201e+07,3.912852e+06,1.089879e+07,NaN
62,01/04/2022,177148.1,24140.5,1.771481e+08,1.730038e+08,4.144284e+06,1.771481e+08,5.319000e+07,5.006397e+07,6.535759e+07,...,4.999168e+07,6.746167e+06,1.930946e+07,2.287784e+07,6.510666e+06,1.719459e+06,2.313127e+07,4.228054e+06,NaN,1.191048e+07
63,01/05/2022,179639.2,23234.2,1.796392e+08,1.753585e+08,4.280751e+06,1.796392e+08,5.273811e+07,4.988679e+07,6.807009e+07,...,5.015035e+07,6.667330e+06,2.012112e+07,2.284153e+07,6.314109e+06,1.779483e+06,2.357864e+07,5.213153e+06,1.203960e+07,1.234998e+07

In [32]:
#Sustituir valores nulos con la MEDIA
#Promedio (mean): Se utiliza para un conjunto de datos más equilibrado sin outliers.
data["salon_ventas"] = data["salon_ventas"].fillna(data["salon_ventas"].mean())
data["tarjetas_debito"] = data["tarjetas_debito"].fillna(data["tarjetas_debito"].mean())

In [31]:
#Sustituir valores nulos con la MEDIANA
##Mediana (median): Se utiliza cuando los datos tienen outliers o una distribución sesgada, ya que es menos sensible a valores extremos.
data["tarjetas_credito"] = data["tarjetas_credito"].fillna(data["tarjetas_credito"].median())
data["otros"] = data["otros"].fillna(data["otros"].median())

In [25]:
#Sustituir valores nulos con un VALOR ESPECÍFICO (or ejemplo, 0)
data["otros_medios"] = data["otros_medios"].fillna(1028013.285)

In [27]:
#Rellenar valores nulos con el VALOR ANTERIOR (forward fill)
data["subtotal_ventas_alimentos_bebidas"] = data["subtotal_ventas_alimentos_bebidas"].fillna(method="ffill")
data["bebidas"] = data["bebidas"].fillna(method="ffill")
data["almacen"] = data["almacen"].fillna(method="ffill")
data["panaderia"] = data["panaderia"].fillna(method="ffill")
data["panaderia"] = data["panaderia"].fillna(method="ffill")
data["lacteos"] = data["lacteos"].fillna(method="ffill")
data["carnes"] = data["carnes"].fillna(method="ffill")
data["verduleria_fruteria"] = data["verduleria_fruteria"].fillna(method="ffill")
data["alimentos_preparados_rotiseria"] = data["alimentos_preparados_rotiseria"].fillna(method="ffill")

<ipython-input-27-8856c85a7e65>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["subtotal_ventas_alimentos_bebidas"] = data["subtotal_ventas_alimentos_bebidas"].fillna(method="ffill")
<ipython-input-27-8856c85a7e65>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["bebidas"] = data["bebidas"].fillna(method="ffill")
<ipython-input-27-8856c85a7e65>:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["almacen"] = data["almacen"].fillna(method="ffill")
<ipython-input-27-8856c85a7e65>:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["panaderia"] = data["panaderia"].fillna(method="ffill")
<ipython-input-27-8856c85a7e65>:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["panaderia"] = data["panaderia"].fillna(method="ffill")
<ipython-input-27-8856c85a7e65>:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["lacteos"] = data["lacteos"].fillna(method="ffill")
<ipython-input-27-8856c85a7e65>:8: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["carnes"] = data["carnes"].fillna(method="ffill")
<ipython-input-27-8856c85a7e65>:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["verduleria_fruteria"] = data["verduleria_fruteria"].fillna(method="ffill")
<ipython-input-27-8856c85a7e65>:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["alimentos_preparados_rotiseria"] = data["alimentos_preparados_rotiseria"].fillna(method="ffill")

In [30]:
##Si queremos sustituir nulos por valores numericos
##string en concreto
data["indumentaria_calzado_textiles_hogar"]=data["indumentaria_calzado_textiles_hogar"].fillna("772871.2876")
data["electronicos_articulos_hogar"]=data["electronicos_articulos_hogar"].fillna("1628423.28")

In [33]:
##Identificar los valores nulos
valores_nulos=data.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              0
lacteos                                0
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         0
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    0
electronicos_articulos_hogar           0
otros                                  0
dtype: int64

In [34]:
data.to_csv('Actividad 3.1.csv', index=False)

# EJEMPLO EN CLASE

In [ ]:
##primer metodo se sustitución
##sustituir valores nulos con promedio o media
##todos los promedios nulos los va a rellenar en la siguente columna, menos los nulos
data3["Superficie"]=data3["Superficie"].fillna(round(data2["Superficie"].mean(),1))

NameError: name 'data3' is not defined

In [ ]:
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

In [ ]:
##Valor nulos con mediana
data3["Precio Venta"]=data3["Precio Venta"].fillna(round(data2["Precio Venta"].mean(),1))
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,NaN,NaN

In [ ]:
##valor nulo en precio venta
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta     578
Vendedor        578
dtype: int64

In [ ]:
##Si queremos sustituir nulos por valores numericos
data3["Fecha Alta"]=data3["Fecha Alta"].fillna(10)
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,NaN,NaN

In [ ]:
##string en concreto
data3["Fecha Venta"]=data3["Fecha Venta"].fillna("2030-06-19 00:00:00")
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,NaN

In [ ]:
##si encuentra un valor nulo lo rellena con lo anterior
##forward fill
data3["Tipo"]=data3["Tipo"].fillna(method="ffill")
data3

<ipython-input-16-1a2d249697f2>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data3["Tipo"]=data3["Tipo"].fillna(method="ffill")

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,NaN

In [ ]:
data3["Operación"]=data3["Operación"].fillna(method="bfill")

<ipython-input-18-ed45762eee0a>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data3["Operación"]=data3["Operación"].fillna(method="bfill")

In [ ]:
data3["Provincia"]=data3["Provincia"].fillna(method="bfill")

<ipython-input-19-e65fbc567d44>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data3["Provincia"]=data3["Provincia"].fillna(method="bfill")

In [ ]:
valores_nulo=data3.isnull().sum()
valores_nulo

Fecha Alta        0
Tipo              0
Operación         0
Provincia         0
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [ ]:
data4=data2.copy()
data4

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN