<a href="https://colab.research.google.com/github/CaroBrambila/Actividad-3.1-y-3.2-Valores-Nulos-/blob/main/Valores_Nulos_equipo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# **Datos de Facturación**

In [29]:
df = pd.read_excel('Datos de Facturación (1).xlsx')
df.head()

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465,C,1.0,2019-09-03 08:58:42,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,F29415,3926,C,1.0,2019-09-03 09:55:14,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,F29416,3926,C,1.0,2019-09-03 13:25:33,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,F29417,3926,C,1.0,2019-09-03 13:33:23,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,F29418,6813,C,2.0,2019-09-03 14:23:45,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0

In [30]:
##Identificar los valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

CVE_DOC              5
CVE_CLPV             0
STATUS               9
CVE_VEND            48
FECHAELAB            2
FECHA_DOC            1
FECHA_ENT            2
FECHA_VEN            0
FECHA_CANCELA    10537
CAN_TOT              6
DES_TOT              1
DES_FIN              3
dtype: int64

In [43]:
data=df.copy()

In [41]:
#Rellenar valores nulos con el VALOR ANTERIOR (forward fill)
##Pq va de uno en uno pero como son faltantes
df["CVE_DOC"] = df["CVE_DOC"].fillna(method="ffill")
#Como son fechas debe y estan registradas por fecha y estan en orden
df["FECHAELAB"] = df["FECHAELAB"].fillna(method="ffill")
df["FECHA_DOC"] = df["FECHA_DOC"].fillna(method="ffill")

<ipython-input-41-8bcf92023ebe>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["CVE_DOC"] = df["CVE_DOC"].fillna(method="ffill")
<ipython-input-41-8bcf92023ebe>:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["FECHAELAB"] = df["FECHAELAB"].fillna(method="ffill")
<ipython-input-41-8bcf92023ebe>:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["FECHA_DOC"] = df["FECHA_DOC"].fillna(method="ffill")

In [46]:
#Sustituir valores nulos con un VALOR ESPECÍFICO (or ejemplo, 0)
##Eligí por "C" ya que la mayoría es E
df["STATUS"] = df["STATUS"].fillna("C")
df["FECHA_CANCELA"] = df["FECHA_CANCELA"].fillna("09/09/2019")

In [40]:
#Sustituir valores nulos con la MEDIA
#Promedio (mean): Se utiliza para un conjunto de datos más equilibrado sin outliers.
df["CVE_VEND"] = df["CVE_VEND"].fillna(df["CVE_VEND"].mean())
df["CAN_TOT"] = df["CAN_TOT"].fillna(df["CAN_TOT"].mean())

In [39]:
#Sustituir valores nulos con la MEDIANA
##Mediana (median): Se utiliza cuando los datos tienen outliers o una distribución sesgada, ya que es menos sensible a valores extremos.
df["DES_TOT"] = df["DES_TOT"].fillna(df["DES_TOT"].median())
df["DES_FIN"] = df["DES_FIN"].fillna(df["DES_FIN"].median())

In [36]:
##string en concreto
df["FECHA_ENT"]=df["FECHA_ENT"].fillna("09/09/2019  12:00:00 a. m.")

In [47]:
##Identificar los valores nulos
valores_nulos=df.isnull().sum()
valores_nulos

CVE_DOC          0
CVE_CLPV         0
STATUS           0
CVE_VEND         0
FECHAELAB        0
FECHA_DOC        0
FECHA_ENT        0
FECHA_VEN        0
FECHA_CANCELA    0
CAN_TOT          0
DES_TOT          0
DES_FIN          0
dtype: int64

# **Detalle precios y productos fabricados 2022**

In [24]:
productos=pd.read_excel('Detalle precios y productos fabricados 2022 (2).xlsx')
productos.head()

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1.0,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1.0,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7.0,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1.0,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2.0,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41

In [25]:
##Identificar los valores nulos
valores_nulos=productos.isnull().sum()
valores_nulos

CVE_DOC                      3
FECHA_DOC                    3
NOMBRE_VENDEDOR              2
NOMBRE_CLIENTE               2
CANT                         7
CVE_ART                      2
DESCR                        2
PRECIO_UNITARIO              2
COSTO_UNITARIO               4
COSTO_UNITARIO_CALCULADO     2
SUBTOTAL_PARTIDA             4
COSTO_TOTAL_CALCULADO        0
MARGEN_UNITARIO_CALCULADO    0
MARGEN_TOTAL_CALCULADO       0
dtype: int64

In [55]:
#Sustituir valores nulos con la MEDIA
#Promedio (mean): Se utiliza para un conjunto de datos más equilibrado sin outliers.
productos["CANT"] = productos["CANT"].fillna(productos["CANT"].mean())
productos["COSTO_UNITARIO"] = productos["COSTO_UNITARIO"].fillna(productos["COSTO_UNITARIO"].mean())
productos["SUBTOTAL_PARTIDA"] = productos["SUBTOTAL_PARTIDA"].fillna(productos["SUBTOTAL_PARTIDA"].mean())

In [51]:
#Sustituir valores nulos con la MEDIANA
##Mediana (median): Se utiliza cuando los datos tienen outliers o una distribución sesgada, ya que es menos sensible a valores extremos.
productos["PRECIO_UNITARIO"] = productos["PRECIO_UNITARIO"].fillna(productos["PRECIO_UNITARIO"].median())
productos["COSTO_UNITARIO_CALCULADO"] = productos["COSTO_UNITARIO_CALCULADO"].fillna(productos["COSTO_UNITARIO_CALCULADO"].median())

In [56]:
#Rellenar valores nulos con el VALOR ANTERIOR (forward fill)
productos["CVE_DOC"] = productos["CVE_DOC"].fillna(method="ffill")
productos["NOMBRE_VENDEDOR"] = productos["NOMBRE_VENDEDOR"].fillna(method="ffill")
productos["NOMBRE_CLIENTE"] = productos["NOMBRE_CLIENTE"].fillna(method="ffill")
productos["FECHA_DOC"] = productos["FECHA_DOC"].fillna(method="ffill")

<ipython-input-56-4c5b59317ca0>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  productos["CVE_DOC"] = productos["CVE_DOC"].fillna(method="ffill")
<ipython-input-56-4c5b59317ca0>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  productos["NOMBRE_VENDEDOR"] = productos["NOMBRE_VENDEDOR"].fillna(method="ffill")
<ipython-input-56-4c5b59317ca0>:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  productos["NOMBRE_CLIENTE"] = productos["NOMBRE_CLIENTE"].fillna(method="ffill")
<ipython-input-56-4c5b59317ca0>:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  productos["FECHA_DOC"] = productos["FECHA_DOC"].fillna(method="ffill")

In [53]:
#DESCR / BAN MICA 120mmØx50mm 850W 440V TTORNILLO
##string en concreto
productos["DESCR"]=productos["DESCR"].fillna("BAN MICA 120mmØx50mm 850W 440V TTORNILLO")
productos["CVE_ART"]=productos["CVE_ART"].fillna("TUA00406")

In [58]:
##Identificar los valores nulos
valores_nulos=productos.isnull().sum()
valores_nulos

CVE_DOC                      0
FECHA_DOC                    0
NOMBRE_VENDEDOR              0
NOMBRE_CLIENTE               0
CANT                         0
CVE_ART                      0
DESCR                        0
PRECIO_UNITARIO              0
COSTO_UNITARIO               0
COSTO_UNITARIO_CALCULADO     0
SUBTOTAL_PARTIDA             0
COSTO_TOTAL_CALCULADO        0
MARGEN_UNITARIO_CALCULADO    0
MARGEN_TOTAL_CALCULADO       0
dtype: int64

# **Gastos y costos 20-23**

In [59]:
gastos = pd.read_excel('Gastos y costos 20-23.xlsx',sheet_name="2021")
gastos.head()

,CALOR Y CONTROL S.A DE C.V,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,SUMA GTO,12942388.82,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,DEDUCCIONES 2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SUMA IVA,1802889.297,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,DESCRIPCION,MP,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA
3,2021-01-01 00:00:00,0001010100750847116902,71B4C8B9-8DAA-47CC-AD47-9DD90AA5AF6B,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,PUE,1,490,78.4,0,0,568.4,568.4,I,Vigente,0
4,2021-01-01 00:00:00,0001010100752163714102,B8AEDE83-CC76-404C-A611-6B5A87BA561F,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,PUE,1,345,55.2,0,0,400.2,400.2,I,Vigente,0

In [68]:
##Eliminar filas innecesarias
data1gastos =pd.read_excel("Gastos y costos 20-23.xlsx",sheet_name="2021", skiprows=3)
data1gastos.head()

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,DESCRIPCION,MP,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA
0,2021-01-01,0001010100750847116902,71B4C8B9-8DAA-47CC-AD47-9DD90AA5AF6B,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,PUE,1.0,490.00,78.40,0.0,0.0,568.4,568.4,I,Vigente,0
1,2021-01-01,0001010100752163714102,B8AEDE83-CC76-404C-A611-6B5A87BA561F,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,PUE,1.0,345.00,55.20,0.0,0.0,400.2,400.2,I,Vigente,0
2,2021-01-01,19788,19B9B2C2-DF58-E24D-B43A-3FC4D5A929E7,ESI9612311E7,"ELECTRONICOS Y SIMILARES, S.A. DE C.V.",COMPRAS,MOTO E7 PLUS AZUL 64GB 4RAM,PUE,1.0,3447.41,551.59,0.0,0.0,3999.0,3999.0,I,Vigente,0
3,2021-01-01,211781,EAB26414-DD9A-4E8F-9F5C-05FE24D98E48,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 6/36 de 03/12/2...,PPD,1.0,5551.38,888.22,0.0,0.0,6439.6,6439.6,I,Vigente,0
4,2021-01-01,211782,C16F79B5-FB35-4BFC-AF84-708B24F500BB,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 6/36 de 03/12/2...,PPD,1.0,5551.98,888.32,0.0,0.0,6440.3,6440.3,I,Vigente,0

In [69]:
##Identificar los valores nulos
valores_nulos=data1gastos.isnull().sum()
valores_nulos

FECHA             0
FOLIO           147
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
DESCRIPCION       0
MP              654
TC                0
IMPORTE           0
IVA               0
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              0
STATUS            0
POLIZA         2372
dtype: int64

In [74]:
#Sustituir valores nulos con un VALOR ESPECÍFICO (or ejemplo, 0)
data1gastos["FOLIO"] = data1gastos["FOLIO"].fillna(102801)
data1gastos = pd.DataFrame({'FOLIO': [np.nan, 102801, np.nan, 102803, np.nan]})

In [86]:
data1gastos = pd.DataFrame({'POLIZA': [np.nan, 2372, np.nan, np.nan, 4390]})

In [78]:
#Rellenar valores nulos con el VALOR ANTERIOR (forward fill)
data1gastos["MP"] = data1gastos["MP"].fillna(method="ffill")

KeyError: 'MP'

In [77]:
##string en concreto
data1gastos["MP"]=data1gastos["MP"].fillna("PUE")

KeyError: 'MP'

In [87]:
##Identificar los valores nulos
valores_nulos=data1gastos.isnull().sum()
valores_nulos

POLIZA    3
dtype: int64